/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: client.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "client.pb-c.h"
void   rpc__write_points_request__init
                     (Rpc__WritePointsRequest         *message)
{
  static const Rpc__WritePointsRequest init_value = RPC__WRITE_POINTS_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__write_points_request__get_packed_size
                     (const Rpc__WritePointsRequest *message)
{
  assert(message->base.descriptor == &rpc__write_points_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__write_points_request__pack
                     (const Rpc__WritePointsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__write_points_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__write_points_request__pack_to_buffer
                     (const Rpc__WritePointsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__write_points_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__WritePointsRequest *
       rpc__write_points_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__WritePointsRequest *)
     protobuf_c_message_unpack (&rpc__write_points_request__descriptor,
                                allocator, len, data);
}
void   rpc__write_points_request__free_unpacked
                     (Rpc__WritePointsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__write_points_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__write_points_response__init
                     (Rpc__WritePointsResponse         *message)
{
  static const Rpc__WritePointsResponse init_value = RPC__WRITE_POINTS_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__write_points_response__get_packed_size
                     (const Rpc__WritePointsResponse *message)
{
  assert(message->base.descriptor == &rpc__write_points_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__write_points_response__pack
                     (const Rpc__WritePointsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__write_points_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__write_points_response__pack_to_buffer
                     (const Rpc__WritePointsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__write_points_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__WritePointsResponse *
       rpc__write_points_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__WritePointsResponse *)
     protobuf_c_message_unpack (&rpc__write_points_response__descriptor,
                                allocator, len, data);
}
void   rpc__write_points_response__free_unpacked
                     (Rpc__WritePointsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__write_points_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_series_request__init
                     (Rpc__QuerySeriesRequest         *message)
{
  static const Rpc__QuerySeriesRequest init_value = RPC__QUERY_SERIES_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__query_series_request__get_packed_size
                     (const Rpc__QuerySeriesRequest *message)
{
  assert(message->base.descriptor == &rpc__query_series_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_series_request__pack
                     (const Rpc__QuerySeriesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_series_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_series_request__pack_to_buffer
                     (const Rpc__QuerySeriesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_series_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QuerySeriesRequest *
       rpc__query_series_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QuerySeriesRequest *)
     protobuf_c_message_unpack (&rpc__query_series_request__descriptor,
                                allocator, len, data);
}
void   rpc__query_series_request__free_unpacked
                     (Rpc__QuerySeriesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_series_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_series_response__init
                     (Rpc__QuerySeriesResponse         *message)
{
  static const Rpc__QuerySeriesResponse init_value = RPC__QUERY_SERIES_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__query_series_response__get_packed_size
                     (const Rpc__QuerySeriesResponse *message)
{
  assert(message->base.descriptor == &rpc__query_series_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_series_response__pack
                     (const Rpc__QuerySeriesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_series_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_series_response__pack_to_buffer
                     (const Rpc__QuerySeriesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_series_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QuerySeriesResponse *
       rpc__query_series_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QuerySeriesResponse *)
     protobuf_c_message_unpack (&rpc__query_series_response__descriptor,
                                allocator, len, data);
}
void   rpc__query_series_response__free_unpacked
                     (Rpc__QuerySeriesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_series_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__config_request__init
                     (Rpc__ConfigRequest         *message)
{
  static const Rpc__ConfigRequest init_value = RPC__CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__config_request__get_packed_size
                     (const Rpc__ConfigRequest *message)
{
  assert(message->base.descriptor == &rpc__config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__config_request__pack
                     (const Rpc__ConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__config_request__pack_to_buffer
                     (const Rpc__ConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__ConfigRequest *
       rpc__config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__ConfigRequest *)
     protobuf_c_message_unpack (&rpc__config_request__descriptor,
                                allocator, len, data);
}
void   rpc__config_request__free_unpacked
                     (Rpc__ConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__config_response__init
                     (Rpc__ConfigResponse         *message)
{
  static const Rpc__ConfigResponse init_value = RPC__CONFIG_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__config_response__get_packed_size
                     (const Rpc__ConfigResponse *message)
{
  assert(message->base.descriptor == &rpc__config_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__config_response__pack
                     (const Rpc__ConfigResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__config_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__config_response__pack_to_buffer
                     (const Rpc__ConfigResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__config_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__ConfigResponse *
       rpc__config_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__ConfigResponse *)
     protobuf_c_message_unpack (&rpc__config_response__descriptor,
                                allocator, len, data);
}
void   rpc__config_response__free_unpacked
                     (Rpc__ConfigResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__config_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_range_request__init
                     (Rpc__QueryRangeRequest         *message)
{
  static const Rpc__QueryRangeRequest init_value = RPC__QUERY_RANGE_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__query_range_request__get_packed_size
                     (const Rpc__QueryRangeRequest *message)
{
  assert(message->base.descriptor == &rpc__query_range_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_range_request__pack
                     (const Rpc__QueryRangeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_range_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_range_request__pack_to_buffer
                     (const Rpc__QueryRangeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_range_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QueryRangeRequest *
       rpc__query_range_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QueryRangeRequest *)
     protobuf_c_message_unpack (&rpc__query_range_request__descriptor,
                                allocator, len, data);
}
void   rpc__query_range_request__free_unpacked
                     (Rpc__QueryRangeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_range_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_range_response__init
                     (Rpc__QueryRangeResponse         *message)
{
  static const Rpc__QueryRangeResponse init_value = RPC__QUERY_RANGE_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__query_range_response__get_packed_size
                     (const Rpc__QueryRangeResponse *message)
{
  assert(message->base.descriptor == &rpc__query_range_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_range_response__pack
                     (const Rpc__QueryRangeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_range_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_range_response__pack_to_buffer
                     (const Rpc__QueryRangeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_range_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QueryRangeResponse *
       rpc__query_range_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QueryRangeResponse *)
     protobuf_c_message_unpack (&rpc__query_range_response__descriptor,
                                allocator, len, data);
}
void   rpc__query_range_response__free_unpacked
                     (Rpc__QueryRangeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_range_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_tag_values_request__init
                     (Rpc__QueryTagValuesRequest         *message)
{
  static const Rpc__QueryTagValuesRequest init_value = RPC__QUERY_TAG_VALUES_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__query_tag_values_request__get_packed_size
                     (const Rpc__QueryTagValuesRequest *message)
{
  assert(message->base.descriptor == &rpc__query_tag_values_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_tag_values_request__pack
                     (const Rpc__QueryTagValuesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_tag_values_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_tag_values_request__pack_to_buffer
                     (const Rpc__QueryTagValuesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_tag_values_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QueryTagValuesRequest *
       rpc__query_tag_values_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QueryTagValuesRequest *)
     protobuf_c_message_unpack (&rpc__query_tag_values_request__descriptor,
                                allocator, len, data);
}
void   rpc__query_tag_values_request__free_unpacked
                     (Rpc__QueryTagValuesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_tag_values_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_tag_values_response__init
                     (Rpc__QueryTagValuesResponse         *message)
{
  static const Rpc__QueryTagValuesResponse init_value = RPC__QUERY_TAG_VALUES_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__query_tag_values_response__get_packed_size
                     (const Rpc__QueryTagValuesResponse *message)
{
  assert(message->base.descriptor == &rpc__query_tag_values_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_tag_values_response__pack
                     (const Rpc__QueryTagValuesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_tag_values_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_tag_values_response__pack_to_buffer
                     (const Rpc__QueryTagValuesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_tag_values_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QueryTagValuesResponse *
       rpc__query_tag_values_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QueryTagValuesResponse *)
     protobuf_c_message_unpack (&rpc__query_tag_values_response__descriptor,
                                allocator, len, data);
}
void   rpc__query_tag_values_response__free_unpacked
                     (Rpc__QueryTagValuesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_tag_values_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_new_point_request__init
                     (Rpc__QueryNewPointRequest         *message)
{
  static const Rpc__QueryNewPointRequest init_value = RPC__QUERY_NEW_POINT_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__query_new_point_request__get_packed_size
                     (const Rpc__QueryNewPointRequest *message)
{
  assert(message->base.descriptor == &rpc__query_new_point_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_new_point_request__pack
                     (const Rpc__QueryNewPointRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_new_point_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_new_point_request__pack_to_buffer
                     (const Rpc__QueryNewPointRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_new_point_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QueryNewPointRequest *
       rpc__query_new_point_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QueryNewPointRequest *)
     protobuf_c_message_unpack (&rpc__query_new_point_request__descriptor,
                                allocator, len, data);
}
void   rpc__query_new_point_request__free_unpacked
                     (Rpc__QueryNewPointRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_new_point_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__query_new_point_response__init
                     (Rpc__QueryNewPointResponse         *message)
{
  static const Rpc__QueryNewPointResponse init_value = RPC__QUERY_NEW_POINT_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__query_new_point_response__get_packed_size
                     (const Rpc__QueryNewPointResponse *message)
{
  assert(message->base.descriptor == &rpc__query_new_point_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__query_new_point_response__pack
                     (const Rpc__QueryNewPointResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__query_new_point_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__query_new_point_response__pack_to_buffer
                     (const Rpc__QueryNewPointResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__query_new_point_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__QueryNewPointResponse *
       rpc__query_new_point_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__QueryNewPointResponse *)
     protobuf_c_message_unpack (&rpc__query_new_point_response__descriptor,
                                allocator, len, data);
}
void   rpc__query_new_point_response__free_unpacked
                     (Rpc__QueryNewPointResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__query_new_point_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc__write_points_request__field_descriptors[1] =
{
  {
    "row",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__WritePointsRequest, row),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__write_points_request__field_indices_by_name[] = {
  0,   /* field[0] = row */
};
static const ProtobufCIntRange rpc__write_points_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__write_points_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.WritePointsRequest",
  "WritePointsRequest",
  "Rpc__WritePointsRequest",
  "rpc",
  sizeof(Rpc__WritePointsRequest),
  1,
  rpc__write_points_request__field_descriptors,
  rpc__write_points_request__field_indices_by_name,
  1,  rpc__write_points_request__number_ranges,
  (ProtobufCMessageInit) rpc__write_points_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__write_points_response__field_descriptors[1] =
{
  {
    "reply",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__WritePointsResponse, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__write_points_response__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange rpc__write_points_response__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__write_points_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.WritePointsResponse",
  "WritePointsResponse",
  "Rpc__WritePointsResponse",
  "rpc",
  sizeof(Rpc__WritePointsResponse),
  1,
  rpc__write_points_response__field_descriptors,
  rpc__write_points_response__field_indices_by_name,
  1,  rpc__write_points_response__number_ranges,
  (ProtobufCMessageInit) rpc__write_points_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_series_request__field_descriptors[1] =
{
  {
    "tags",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QuerySeriesRequest, tags),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_series_request__field_indices_by_name[] = {
  0,   /* field[0] = tags */
};
static const ProtobufCIntRange rpc__query_series_request__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_series_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QuerySeriesRequest",
  "QuerySeriesRequest",
  "Rpc__QuerySeriesRequest",
  "rpc",
  sizeof(Rpc__QuerySeriesRequest),
  1,
  rpc__query_series_request__field_descriptors,
  rpc__query_series_request__field_indices_by_name,
  1,  rpc__query_series_request__number_ranges,
  (ProtobufCMessageInit) rpc__query_series_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_series_response__field_descriptors[1] =
{
  {
    "reply",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QuerySeriesResponse, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_series_response__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange rpc__query_series_response__number_ranges[1 + 1] =
{
  { 4, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_series_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QuerySeriesResponse",
  "QuerySeriesResponse",
  "Rpc__QuerySeriesResponse",
  "rpc",
  sizeof(Rpc__QuerySeriesResponse),
  1,
  rpc__query_series_response__field_descriptors,
  rpc__query_series_response__field_indices_by_name,
  1,  rpc__query_series_response__number_ranges,
  (ProtobufCMessageInit) rpc__query_series_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__config_request__field_descriptors[2] =
{
  {
    "path",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ConfigRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ConfigRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__config_request__field_indices_by_name[] = {
  1,   /* field[1] = name */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange rpc__config_request__number_ranges[2 + 1] =
{
  { 5, 0 },
  { 11, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.ConfigRequest",
  "ConfigRequest",
  "Rpc__ConfigRequest",
  "rpc",
  sizeof(Rpc__ConfigRequest),
  2,
  rpc__config_request__field_descriptors,
  rpc__config_request__field_indices_by_name,
  2,  rpc__config_request__number_ranges,
  (ProtobufCMessageInit) rpc__config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__config_response__field_descriptors[1] =
{
  {
    "reply",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ConfigResponse, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__config_response__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange rpc__config_response__number_ranges[1 + 1] =
{
  { 6, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__config_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.ConfigResponse",
  "ConfigResponse",
  "Rpc__ConfigResponse",
  "rpc",
  sizeof(Rpc__ConfigResponse),
  1,
  rpc__config_response__field_descriptors,
  rpc__config_response__field_indices_by_name,
  1,  rpc__config_response__number_ranges,
  (ProtobufCMessageInit) rpc__config_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_range_request__field_descriptors[1] =
{
  {
    "metric_tags",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QueryRangeRequest, metric_tags),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_range_request__field_indices_by_name[] = {
  0,   /* field[0] = metric_tags */
};
static const ProtobufCIntRange rpc__query_range_request__number_ranges[1 + 1] =
{
  { 7, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_range_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QueryRangeRequest",
  "QueryRangeRequest",
  "Rpc__QueryRangeRequest",
  "rpc",
  sizeof(Rpc__QueryRangeRequest),
  1,
  rpc__query_range_request__field_descriptors,
  rpc__query_range_request__field_indices_by_name,
  1,  rpc__query_range_request__number_ranges,
  (ProtobufCMessageInit) rpc__query_range_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_range_response__field_descriptors[1] =
{
  {
    "reply",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QueryRangeResponse, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_range_response__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange rpc__query_range_response__number_ranges[1 + 1] =
{
  { 8, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_range_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QueryRangeResponse",
  "QueryRangeResponse",
  "Rpc__QueryRangeResponse",
  "rpc",
  sizeof(Rpc__QueryRangeResponse),
  1,
  rpc__query_range_response__field_descriptors,
  rpc__query_range_response__field_indices_by_name,
  1,  rpc__query_range_response__number_ranges,
  (ProtobufCMessageInit) rpc__query_range_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_tag_values_request__field_descriptors[1] =
{
  {
    "tag",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QueryTagValuesRequest, tag),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_tag_values_request__field_indices_by_name[] = {
  0,   /* field[0] = tag */
};
static const ProtobufCIntRange rpc__query_tag_values_request__number_ranges[1 + 1] =
{
  { 9, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_tag_values_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QueryTagValuesRequest",
  "QueryTagValuesRequest",
  "Rpc__QueryTagValuesRequest",
  "rpc",
  sizeof(Rpc__QueryTagValuesRequest),
  1,
  rpc__query_tag_values_request__field_descriptors,
  rpc__query_tag_values_request__field_indices_by_name,
  1,  rpc__query_tag_values_request__number_ranges,
  (ProtobufCMessageInit) rpc__query_tag_values_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_tag_values_response__field_descriptors[1] =
{
  {
    "reply",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QueryTagValuesResponse, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_tag_values_response__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange rpc__query_tag_values_response__number_ranges[1 + 1] =
{
  { 10, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_tag_values_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QueryTagValuesResponse",
  "QueryTagValuesResponse",
  "Rpc__QueryTagValuesResponse",
  "rpc",
  sizeof(Rpc__QueryTagValuesResponse),
  1,
  rpc__query_tag_values_response__field_descriptors,
  rpc__query_tag_values_response__field_indices_by_name,
  1,  rpc__query_tag_values_response__number_ranges,
  (ProtobufCMessageInit) rpc__query_tag_values_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_new_point_request__field_descriptors[1] =
{
  {
    "tag",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QueryNewPointRequest, tag),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_new_point_request__field_indices_by_name[] = {
  0,   /* field[0] = tag */
};
static const ProtobufCIntRange rpc__query_new_point_request__number_ranges[1 + 1] =
{
  { 11, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_new_point_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QueryNewPointRequest",
  "QueryNewPointRequest",
  "Rpc__QueryNewPointRequest",
  "rpc",
  sizeof(Rpc__QueryNewPointRequest),
  1,
  rpc__query_new_point_request__field_descriptors,
  rpc__query_new_point_request__field_indices_by_name,
  1,  rpc__query_new_point_request__number_ranges,
  (ProtobufCMessageInit) rpc__query_new_point_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__query_new_point_response__field_descriptors[1] =
{
  {
    "reply",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__QueryNewPointResponse, reply),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__query_new_point_response__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange rpc__query_new_point_response__number_ranges[1 + 1] =
{
  { 12, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__query_new_point_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.QueryNewPointResponse",
  "QueryNewPointResponse",
  "Rpc__QueryNewPointResponse",
  "rpc",
  sizeof(Rpc__QueryNewPointResponse),
  1,
  rpc__query_new_point_response__field_descriptors,
  rpc__query_new_point_response__field_indices_by_name,
  1,  rpc__query_new_point_response__number_ranges,
  (ProtobufCMessageInit) rpc__query_new_point_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor rpc__greeter__method_descriptors[6] =
{
  { "WritePoints", &rpc__write_points_request__descriptor, &rpc__write_points_response__descriptor },
  { "QuerySeries", &rpc__query_series_request__descriptor, &rpc__query_series_response__descriptor },
  { "Config", &rpc__config_request__descriptor, &rpc__config_response__descriptor },
  { "QueryRange", &rpc__query_range_request__descriptor, &rpc__query_range_response__descriptor },
  { "QueryTagValues", &rpc__query_tag_values_request__descriptor, &rpc__query_tag_values_response__descriptor },
  { "QueryNewPoint", &rpc__query_new_point_request__descriptor, &rpc__query_new_point_response__descriptor },
};
const unsigned rpc__greeter__method_indices_by_name[] = {
  2,        /* Config */
  5,        /* QueryNewPoint */
  3,        /* QueryRange */
  1,        /* QuerySeries */
  4,        /* QueryTagValues */
  0         /* WritePoints */
};
const ProtobufCServiceDescriptor rpc__greeter__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "rpc.Greeter",
  "Greeter",
  "Rpc__Greeter",
  "rpc",
  6,
  rpc__greeter__method_descriptors,
  rpc__greeter__method_indices_by_name
};
void rpc__greeter__write_points(ProtobufCService *service,
                                const Rpc__WritePointsRequest *input,
                                Rpc__WritePointsResponse_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &rpc__greeter__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__greeter__query_series(ProtobufCService *service,
                                const Rpc__QuerySeriesRequest *input,
                                Rpc__QuerySeriesResponse_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &rpc__greeter__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__greeter__config(ProtobufCService *service,
                          const Rpc__ConfigRequest *input,
                          Rpc__ConfigResponse_Closure closure,
                          void *closure_data)
{
  assert(service->descriptor == &rpc__greeter__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__greeter__query_range(ProtobufCService *service,
                               const Rpc__QueryRangeRequest *input,
                               Rpc__QueryRangeResponse_Closure closure,
                               void *closure_data)
{
  assert(service->descriptor == &rpc__greeter__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__greeter__query_tag_values(ProtobufCService *service,
                                    const Rpc__QueryTagValuesRequest *input,
                                    Rpc__QueryTagValuesResponse_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &rpc__greeter__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__greeter__query_new_point(ProtobufCService *service,
                                   const Rpc__QueryNewPointRequest *input,
                                   Rpc__QueryNewPointResponse_Closure closure,
                                   void *closure_data)
{
  assert(service->descriptor == &rpc__greeter__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__greeter__init (Rpc__Greeter_Service *service,
                         Rpc__Greeter_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &rpc__greeter__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
